- src: geerlingguy.php
  version: 4.2.0
- src: geerlingguy.mysql
  version: 3.1.0
- src: geerlingguy.apache
  version: 3.1.0
- src: Oefenweb.swapfile
  version: v2.0.26
- src: geerlingguy.nginx
  version: 2.7.0
- src: geerlingguy.certbot
  version: 3.1.0