apache_listen_ip: "127.0.0.1"
apache_listen_port: 8080
apache_create_vhosts: true
apache_remove_default_vhost: true
apache_packages:
  - apache2
  - apache2-utils
  - libapache2-mod-php
apache_mods_enabled:
  - rewrite.load
  - remoteip.load
  - headers.load
  - php7.2.load
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html index.htm
apache_vhosts_ssl: []
apache_vhosts:
  - servername: "{{ server_name }}"
    apache_listen_ip: "127.0.0.1"
    apache_listen_port: 8080
    documentroot: "{{ wordpress_root }}"
    extra_parameters: |
      KeepAlive On
      KeepAliveTimeout 60
      RemoteIPHeader X-Real-IP
      SetEnv HTTPS "on"     
      SetEnv HTTP_HOST "{{ server_name }}"     
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
